export const defaultThemes = {
  colors: {
    "yellow-dark": "#C47F17",
    yellow: "#DBAC2C",
    "yellow-light": "#F1E9C9",
    "purple-dark": "#4B2995",
    purple: "#8047F8",
    "purple-light": "#EBE5F9",
    "base-title": "#272221",
    "base-subtitle": "#403937",
    "base-text": "#574F4D",
    "base-label": "#8D8686",
    "base-hover": "#D7D5D5",
    "base-button": "#E6E5E5",
    "base-input": "#EDEDED",
    "base-card": "#F3F2F2",
    background: "#FAFAFA",
    white: "#FFFFFF",
  },
  "font-size": {
    "title-xl": "3rem",
    "title-l": "2rem",
    "title-m": "1.5rem",
    "title-s": "1.2rem",
    "title-xs": "1.1rem",
    "text-l": "1.2rem",
    "text-m": "1rem",
    "text-s": "0.9rem",
    "text-xs": "0.8rem",
    tag: "0.7rem",
    "button-g": "0.9rem",
    "button-m": "0.8rem",
  },
};
